### ISSUE TITLE
Docs Website Changes

### ISSUE THREAD

**Issue by sandresen1** [macrosynergy/macrosynergy#1180]
- Remove dropdown menu for "Package Documentation"
- Each dropdown arrow for the modules should be interactive (Should show the user whether the menu is collapsed or open e.g. side arrow and down arrow)
- Contents menu on the right should only show current function and nothing else
- All code text is in text boxes which looks tacky

(Please add to this anything you think needs improving)

**Comment by Magnus167** [comment]
Closed by #1400 , #1338, and #1289
