### ISSUE TITLE
Panel calculator cannot assign series alone

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#1664]
In panel_calculator, single series (as opposed to panels) are marked with an "i". However, is used without other panels this leads to errors.

This is undesirable, because often we want to "localize" global variables, i.e., assign a global variable that applies equally to many cross sections to each cross section.

Thus, the below convoluted operation works:

![Image](https://github.com/macrosynergy/macrosynergy/assets/27678335/bd9a293c-629a-4bf0-854b-7ad74e49dede)

But the simple assignment fails:

![Image](https://github.com/macrosynergy/macrosynergy/assets/27678335/66af0ae0-713c-4602-bfc5-7ae6a11e69ff)

**Comment by emhbrine** [comment]
Fixed with
