### ISSUE TITLE
basket_performance creates zeroes

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#255]
Basket carry calculates to zero for Latam FX in Jupyter/MSPack application.

![image](https://user-images.githubusercontent.com/27678335/152981753-5dee992b-9ab0-452c-9d31-cae2f04c63f9.png)

**Comment by Ksteeds** [comment]
Believe the problem has been solved. Ascribed to insufficient assert statements.

The parameter 'weights' is used incorrectly. The correct parameter to use is 'weight_meth'.

**Comment by Ksteeds** [comment]
Added further assertions to catch future parameter confusion.

**Comment by Ksteeds** [comment]
Work complete. Error addressed.
