### ISSUE TITLE
NaivePnL/ make_pnl: implement pass-through arguments

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#299]
:param <int> min_obs: the minimum number of observations required to calculate
            zn_scores. Default is 252.
            # Todo: implement in function
        :param <bool> iis: if True (default) zn-scores are also calculated for the initial
            sample period defined by min-obs, on an in-sample basis, to avoid losing history.
            # Todo: implement in function
        :param <str> neutral: method to determine neutral level. Default is 'zero'.
            Alternatives are 'mean' and "median".
            # Todo: implement in function
        :param <float> thresh: threshold value beyond which scores are winsorized,
            i.e. contained at that threshold. Therefore, the threshold is the maximum absolute
            score value that the function is allowed to produce. The minimum threshold is 1
            standard deviation.
            # Todo: implement in function

**Comment by Ksteeds** [comment]
Linked to pending Pull Request.
