### ISSUE TITLE
CategoryRelations: erroneous zero values emerging in plot

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#338]
It seems that either at frequency conversion or at another transformations the dataframe of the CategoryRelations class creates zeroes that should not exist. The below chart has been created with JPMaQS data. Please check and prevent the creation of these zeroes as they mislead analyses.

![image](https://user-images.githubusercontent.com/27678335/166905124-2a848f0d-4b9f-4783-aea0-ae8f0763a5b2.png)

cids_g3eq = ["EUR", "JPY", "USD"]
cids_dmeq = ["AUD", "CAD", "CHF", "GBP", "SEK"]
cids_emeq = ["BRL", "INR", "KRW", "MXN", "MYR", "SGD", "THB", "TRY", "TWD", "ZAR"]
cids_eq = cids_g3eq + cids_dmeq + cids_emeq

xcats_rdhi = ["CPIH_SA_P1M1ML12_D1M1ML3", "EQXR_NSA"]
dfxx = dfx[~(dfx.value == 0)]

xcats_sel = xcats_rdhi
cids_sel = cids_eq
cr = msp.CategoryRelations(
    dfxx,
    xcats=xcats_sel,
    cids=cids_sel,
    freq="M",
    lag=1,
    xcat_aggs=["last", "sum"],
    start="2000-01-01",
    xcat_trims=[None, None],
)
cr.reg_scatter(
    labels=False,
    coef_box="lower left",
    title=None,
    xlab=None,
    ylab=None,
)

**Comment by Ksteeds** [comment]
Prematurely closed the Pull Request.

**Comment by Ksteeds** [comment]
Linked to the latest Pull Request.
