### ISSUE TITLE
make_zn_score: sequential estimation needs to increase speed with added parameter

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#342]
At the moment choosing sequential=True makes the function too slow for large panels.
The solution could be an added parameter est_freq="m", with options "w", "q" and "a" that govern the frequency at which the means and standard deviations are estimated (and subsequently forward-filled.

Beyond, the function also runs very slow when `sequential=False` is chosen, which suggests that the calculation is very inefficient.

**Comment by Ksteeds** [comment]
Tied to the latest Pull Request.
