### ISSUE TITLE
Communal sample period feature

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#441]
Functions with comparable statistics should have the parameter

cosp = False (communal sample period)

If cosp = True the comparative statistics are calculated only for periods for which data are available for all compared instances (cross-sections, siganls etc.)

This would be useful for
signal_return()
naive_pnl()

**Comment by Ksteeds** [comment]
Determine the dates of the union prior to reduce_df() being applied.

**Comment by Ksteeds** [comment]
Is communal_sampling required for Naive_PnL ?
Firstly, reduce_df is applied to all signals and the return type whereby the start & end date can be specified. Admittedly, this will be applied on the category level only but the PnL statistic is being computed on the Panel level ? In addition, plotting of the PnL can also be adjusted to focus on specific intervals.

Secondly, the method evaluate_PnL() also receives start & end parameters to control the period the statistics are computed over. And, if a single category is passed and all cross-sections, all cross-sections can be reduced to a specified time-horizon in which the statistics will be calculated over.

I would have thought if a specific cross-section is overly volatile or suffering from idiosyncrasies, would it be included on a PnL method where comparing PnL's against various signals ?

Let me know your thoughts.

**Comment by Ksteeds** [comment]
cid                      AUD       CAD       EUR       GBP       NZD       USD
Return (pct ar)    
St. Dev. (pct ar)  
Sharpe Ratio        
Sortino Ratio      
Max 21-day draw   
Max 6-month draw   
EUR_EQXR correl    
USD_EQXR correl
