### ISSUE TITLE
view timelines: add separate facet_size argument if possible 

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#446]
msp.view_timelines  - the function has size as input parameter, but it is irrelevant for facet grid (only relevant for single chart), so passing any size vector for multiple charts  is not changing size of separate charts – the charts come out in pre- fixed sized (looks like optimized for 3 columns). Not sure if you want to look at this, just mentioning it
Looks like aspect  is changing the length of the charts, and height also stretches the charts. However if I change aspect and height, the font becomes very small. Anyway aspect/height  does not seem most natural way to change the size of separate files.

**Comment by Magnus167** [comment]
To be closed by #684
