### ISSUE TITLE
update_df(dfx, dfa) replaces dfx with dfa on specific occasion

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#449]
code for replications

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
import yaml

import macrosynergy.management as msm
import macrosynergy.panel as msp
import macrosynergy.signal as mss
import macrosynergy.pnl as msn

from macrosynergy.dataquery import api
from macrosynergy.management.dq import DataQueryInterface

# Cross sections

cids_dm = ["AUD", "EUR", "GBP", "JPY", "USD"]
cids_em = ["BRL", "KRW", "ZAR"]
cids = cids_dm + cids_em
cids_dmx = cids_dm + ["USB"]  # adds pseudo cross section of U.S. bonds-based breakeven

# Categories

main = [
    "IMPINFB2Y_NSA",
    "IMPINFB5Y_NSA",
    "IMPINFS2Y_NSA",
    "IMPINFS5Y_NSA",
    "CPIH_SA_P1M1ML12",
    "CPIH_SJA_P3M3ML3AR",
    "CPIH_SJA_P6M6ML6AR",
    "CPIC_SA_P1M1ML12",
    "CPIC_SJA_P3M3ML3AR",
    "CPIC_SJA_P6M6ML6AR",
    "INFTEFF_NSA",
    "INFTARGET_NSA",
    "INFE1Y_JA",
    "INFE5Y_JA",
]
xtra = [
    "RYLDIRS02Y_NSA",
    "RYLDIRS05Y_NSA",
]
rets = ["DU02YXR_NSA", "DU05YXR_NSA", "DU02YXR_VT10", "DU05YXR_VT10"]

xcats = main + xtra + rets

# Resultant tickers

tickers = [cid + "_" + xcat for cid in cids for xcat in xcats]
print(f"Maximum number of tickers is {len(tickers)}")

path = "..//data//"
with open(f"{path}config.yml", "r") as f:
    cf = yaml.load(f, Loader=yaml.FullLoader)

oauth_id = cf["ralph_oauth"]["id"]  # replace by your DataQuery id
oauth_secret = cf["ralph_oauth"]["secret"]  # replace by your DataQuery secret

with api.Interface(oauth=True, client_id=oauth_id, client_secret=oauth_secret) as dq:
    start = timer()
    assert dq.check_connection()
    df = dq.download(
        tickers=tickers,
        start_date="2000-01-01",
        suppress_warning=True,
        metrics=["value", "eop_lag", "mop_lag"],
    )
    assert isinstance(df, pd.DataFrame) and not df.empty
    end = timer()

print("Download time from DQ: " + str(timedelta(seconds=end - start)))
print("Last updated:", date.today())

dfa = dfx[
    (dfx["cid"] == "USD") & (dfx["xcat"].isin(["IMPINFB2Y_NSA", "IMPINFB5Y_NSA"]))
]
dfa["cid"] = "USB"
dfa["xcat"] = dfa["xcat"].str.replace("IMPINFB", "IMPINFS")
dfx = msm.update_df(dfx, dfa)

dfa = dfx[dfx["cid"] == "USD"]
dfa["cid"] = "USB"
dfa
dfx = msm.update_df(dfx, dfa)

**Comment by Ksteeds** [comment]
Tied to #450 PR.
