### ISSUE TITLE
Allow adding panel average to view_timelines

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#45]
- [x] Allow plotting a cross-average average timeline (based on available cross-sections) to each facet axes, for one category only.
- [x] xcats order is not respected for hue in line charts but set alphabetically, leading to inconsistencies with xcat_labels

**Comment by Ksteeds** [comment]
2nd task I do not think occurs - xcats do not appear to be ordered alphabetically but instead match the order received which should match the xcat_label parameter if defined.
