### ISSUE TITLE
view_ranges string error

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#452]
Just run view_ranges script:

TypeError: 'str' object is not callable

**Comment by Ksteeds** [comment]
Not encountering any issues in the IDE.

**Comment by rsueppel** [comment]
![image](https://user-images.githubusercontent.com/27678335/184127740-fc4bdd07-4755-4ae8-a7bf-7b545c1d3618.png)

**Comment by Ksteeds** [comment]
Resolved - outdated pandas version. Changing requirements.txt file.
