### ISSUE TITLE
check_availability throws error in visual_paneldates heatmap with enddates

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#472]
error is in line 121 and arises when passing the dataframe from check_enddates()

this can be seen in the example code of check_availability.py and occurs across notebooks since the update of check_availability, meaning it is probably related to the new calculation of dates.

**Comment by Ksteeds** [comment]
Believe it was ascribed to the type of the column DataFrame. Previously, Int64 and required np.int64.
