### ISSUE TITLE
category relations line 387 causes errors with NAs

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#478]
data_table = self.corr_probability(df_probability=[dfx1, dfx2],
                                                   time_period="",
                                                   coef_box_loc=coef_box)

also 476 would throw error with dropna fix

**Comment by Ksteeds** [comment]
NaN values will exist if, upon instantiation, the two parameter xcat1_chg and xcat_trims are both set to None. NaN values will not be removed by categories_df() function.

**Comment by Ksteeds** [comment]
After changes, there should not be any NaN values in self.df.
