### ISSUE TITLE
check_availability bug still alive and kicking

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#496]
ValueError: cannot convert to 'int32'-dtype NumPy array with missing values. Specify an appropriate 'na_value' for this dtype

![image](https://user-images.githubusercontent.com/27678335/191007965-215134f0-8fcc-48ba-860e-dd01c131c997.png)

**Comment by Magnus167** [comment]
Please also note, that the [MSPack.ipynb](https://github.com/macrosynergy/community/blob/develop/Helpful%20notebooks/MSPack.ipynb) requires YAML (PyYAML), which is not included in the current [requirements.txt](https://github.com/macrosynergy/macrosynergy/blob/develop/requirements.txt).

**Comment by rsueppel** [comment]
I figured out that the bug occurs when you want to visualize a large number of categories.
In my notebook I can call the function with 20 categories, but it throws an error with 27.

![image](https://user-images.githubusercontent.com/27678335/192333827-57110e39-c3ae-45d1-967c-be00f352bdc7.png)

![image](https://user-images.githubusercontent.com/27678335/192333939-f3786c09-2114-41f8-b229-8743c12d1d36.png)
