### ISSUE TITLE
Documentation: README.md file

### ISSUE THREAD

**Issue by lsimonsen** [macrosynergy/macrosynergy#505]
Enhance the README.md file with following content:

1. Additional examples of how to download data from DataQuery. Especially how to download panels instead of single tickers.
2. Add example of use for the other sub-packages of `pnl`, `management`, `panel`, and `signal`.
3. Add automatic [codecov](https://about.codecov.io/) testing of our package to the [README.md](https://github.com/macrosynergy/macrosynergy/blob/develop/README.md) file. See the example in the [Pandas README file](https://github.com/pandas-dev/pandas) for an example.

**Comment by Magnus167** [comment]
Closed by @CyrusYavariMacro in PR #540
