### ISSUE TITLE
Tests: Integration tests using data from JPMaQS via DQ

### ISSUE THREAD

**Issue by lsimonsen** [macrosynergy/macrosynergy#509]
Using the DataQuery interface to download JPMaQS data, run the functionality of the code with the data.

Tests must be generic enough to handle outliers and issue with the data.

**Comment by Magnus167** [comment]
Closed here ? https://github.com/macrosynergy/macrosynergy/blob/67fb077e2f7e1424d7c1324f58ba55608c4c437d/tests/integration/dataquery/test_dataquery.py#L29
