### ISSUE TITLE
Code format: apply black

### ISSUE THREAD

**Issue by lsimonsen** [macrosynergy/macrosynergy#510]
Implement the `black` code format across our code base. One subpackage at a time.

**Comment by Magnus167** [comment]
Would be closed by something to the effect of [feature/apply_codeformat_workflow](https://github.com/macrosynergy/macrosynergy/tree/feature/apply_codeformat_workflow), from #775 . 
However, seems too impractical to implement this way. Better method might be to use directives from the [`pyproject.toml`](https://github.com/macrosynergy/macrosynergy/blob/develop/pyproject.toml) or a [pre-commit](https://pre-commit.com/),

**Comment by Magnus167** [comment]
Would be closed by something to the effect of [feature/apply_codeformat_workflow](https://github.com/macrosynergy/macrosynergy/tree/feature/apply_codeformat_workflow), from #775 . 
However, seems too impractical to implement this way. Better method might be to use directives from the [`pyproject.toml`](https://github.com/macrosynergy/macrosynergy/blob/develop/pyproject.toml) or a [pre-commit](https://pre-commit.com/),
