### ISSUE TITLE
view_timelines runs very very slowly now

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#515]
Check on MSPack
runtime almost 1 min about 10x longer than it used to a week ago

Larger panels in other notebooks take 5-10 mins

**Comment by Magnus167** [comment]
On changing the versions of some of the packages/dependencies used, I am able to get the runtime down to under 10 seconds again.
As of now, these versions allow the function to run faster:
```
numpy==1.22.4
numexpr==2.8.1
scipy==1.7.3
matplotlib==3.5.1
scikit-learn==1.0.2
seaborn==0.11.2
pandas==1.4.2
statsmodels==0.13.2
```
