### ISSUE TITLE
category_relations: check if NAs are stored and (or) plotted as zeroes

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#526]
I see a large number of zero values in plots, more than plausibly are in the data.
The suspicion is that NAs (of which there are many) are treated as zeroes 

![image](https://user-images.githubusercontent.com/27678335/192842227-f34ec06e-ff90-4152-bd30-b0ce49e462f3.png)

**Comment by Magnus167** [comment]
Unit test for this issue/fix is still required

**Comment by Magnus167** [comment]
Marking as stale
