### ISSUE TITLE
unit_target_position not named correctly 

### ISSUE THREAD

**Issue by CyrusYavariMacro** [macrosynergy/macrosynergy#539]
Also not passing test, specifically test modify signals

**Comment by CyrusYavariMacro** [comment]
When min obs is zero the expanding stat function does not work.
The issue starts with,
  first_observation = df.dropna(axis=0, how='all').index[0]
    # Adjust for individual cross-sections' series commencing at different dates.
    first_estimation = df.dropna(axis=0, how='all').index[min_obs]
as when min_obs is zero they are the same therefore,
    obs_index = next(iter(np.where(df.index == first_observation)))[0]
    est_index = next(iter(np.where(df.index == first_estimation)))[0]
are the same.
            df_out = df_out.fillna(method="bfill", limit=(est_index - obs_index))
So in this line limit = 0 but according to pandas doccumentation 
limitint, default None
If method is specified, this is the maximum number of consecutive NaN values to forward/backward fill. In other words, if there is a gap with more than this number of consecutive NaNs, it will only be partially filled. If method is not specified, this is the maximum number of entries along the entire axis where NaNs will be filled. Must be greater than 0 if not None.
Limit can not be zero

**Comment by Ksteeds** [comment]
Thanks a lot Cyrus - very helpful. Will change the code tomorrow.

**Comment by Magnus167** [comment]
Closed by #793
