### ISSUE TITLE
CategoryRelations xcat_aggs bug 

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#553]
The use of the aggregation option of the class instantiation reveals a really bad and consequential bug.
In particular, if I sum one of the two categories, the other is summed as well, rather than aggregated as instructed.

Here is a chart with xcat_aggs=["last", "mean"]
![image](https://user-images.githubusercontent.com/27678335/194716300-4f00fe27-4537-4cbd-9b0f-99cd41e5faea.png)

and here one with xcat_aggs=["last", "sum"]
![image](https://user-images.githubusercontent.com/27678335/194716343-1855898e-a1ed-4190-9a57-42ad6d6ffeb4.png)

Both axes seem to sum the daily data and the correlation changes.

**Comment by Magnus167** [comment]
Bug fixes in [Pull Request #558](https://github.com/macrosynergy/macrosynergy/pull/558) fixes the bug
