### ISSUE TITLE
new class: SignalsReturns (complementing SignalReturnRelations)

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#662]
new class: SignalsReturns (complementing SignalReturnRelations)

    Class for analysing and visualizing signal and a return series.

    :param <pd.Dataframe> df: standardized DataFrame with the following necessary
        columns: 'cid', 'xcat', 'real_date' and 'value.
    :param <str, List[str]> rets: one or several target return categories.
    :param <str, List[str]> sigs: list of signal categories to be considered
    :param <int, List[int[> signs: list of signs (direction of impact) to be applied, corresponding to signs.
		Default is 1. i.e. impact is supposed to be positive.
		When -1 is chosen for one or all list elements the signal category
		hat category is taken in negative terms.
    :param <int> slip: slippage of signal application in days. This effectively lags
	the signal series, i.e. values are recorded on a future date, simulating
	time it takes to trade on the signal
    :param <bool> cosp: If True the comparative statistics are calculated only for the
        "communal sample periods", i.e. periods and cross-sections that have values
        for all compared signals. Default is False.
    :param <str> start: earliest date in ISO format. Default is None in which case the
        earliest date available will be used.
    :param <str> end: latest date in ISO format. Default is None in which case the
        latest date in the df will be used.
    :param <dict> blacklist: cross-sections with date ranges that should be excluded from
        the data frame. If one cross-section has several blacklist periods append numbers
        to the cross-section code.
    :param <str, List[str]> freqs: letters denoting frequency at which the series are to be sampled.
        This must be one of 'D', 'W', 'M', 'Q', 'A'. Default is 'M'.
        The return series will always be summed over the sample period.
        The signal series will be aggregated according to the values of `agg_sigs`.
    :param <int, List[int[> agg_sigs: aggregation method applied to the signal values in down-
        sampling. The default is "last". Alternatives are "mean", "median" and "sum".
        If a single aggregation type is chosen for multiple signal categories it is applied to all of them.
  

The differences between SignalsReturns and the current SignalReturn are the following:
	[1] the new class instantiation only stores signals and returns but calculate no statistics
	[2] the methods calculate and display essentially the result of a signal selected statistic
	    for a wider range of signals than would be manageable for SignalReturn
	[3] some of the arguments are added or changed for the generation of multiple signal versions
	    Thus the number of versions would be len(sigs) x len(rest) x len(agg_sigs) x len(freqs)

The following methods should be applied to the class.

.single_relation_table(ret=None,  xcat=None,  freq=None,  agg_sigs=None)

 :param <str> ret: single return category. If None it chooses the first or only one entered at class instantiation.
 :param <str> xcat: single feature category. If None it chooses the first or only one entered at class instantiation.
 :param <str> freq: single frequency. If None it chooses the default or first or only one entered at class instantiation.
 :param <str> agg_sigs: single aggregation. If None it chooses the default or first or only one entered at class instantiation.

return: table similar to signals_table() of SignalReturnRelations

.multiple_relations_table(rets=None,  xcats=None,  freqs=None,  agg_sigs=None)

 :param <str, List[str]> rets: return categories. If None all available are shown.
 :param <str, List[str]> xcats: feature categories. If None all available are shown.
 :param <str, List[str]> freqs: frequencies. If None all available are shown.
 :param <str, List[str]> agg_sigs: aggregations. If None all available are shown.

return: table similar to summary_table() of SignalReturnRelations
row indices are <xcat>/<ret> (<freq>/<agg>)

.single_statistic_table(stat, type="panel", rows=None, columns=None, heatmap=False, title=None)

:param <str> stat: type of statistic to be displayed. (this can be any of the column names of summary_table)
:param <str> type: type of the statistic displayed. This can be based on the overall panel ("panel", default), an average of annual panels (mean_years), an average of cross-sectional relations ("mean_cids"), the positive ratio across years("pr_years"), positive ratio across sections ("pr_cids").
:param <List[str]> rows: row indices, which can be return categories, feature categories, frequencies and/or aggregations. The choice is made through a list of one or more of "xcat", "ret", "freq" and "agg_sigs". The default is ["xcat", "agg_sigs"] resulting in index strings <xcat> (<agg_signs>) or <xcat> if only one aggregation is available. 
across sections ("pr_cids").
:param <List[str]> columns: column indices, which can be return categories, feature categories, frequencies and/or aggregations. The choice is made through a list of one or more of "xcat", "ret", "freq" and "agg_sigs". The default is ["ret", "freq] resulting in index strings <cid> (<freq>) or <cid> if only one frequency is available.

**Comment by rsueppel** [comment]
On output formats

multiple_relations_table
row label
"XR/CRY/last/M"
rearrange in more intuitive form
"M: CRY/last => XR"


single_relation_table
row names not "panel" but the relation that is shown in the same form as multiple_relations_table

single_statistic_table
row and column names names should reflect the order of the inputs in the `rows` argument.


General question:

What would be the best ways of visualizing the three output tables?

**Comment by sandresen1** [comment]
Look at unit tests for Bal_acc, Pearson and Kendall which test the value independently of everything else in the package
