### ISSUE TITLE
Enhance flexibility of basket calculation in `make_relative_value`

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#683]
So far the `basket` argument can only take cross-sections for basket formation that are also in `cids`, i.e. a subset. 

It should also allow other cross-sections in the data frame.

**Comment by Magnus167** [comment]
The function already has an implicit override--
```python
if cids is None:
  # All cross-sections available - union across categories.
  cids = list(dfx['cid'].unique())
```
Adding an argument to make this behaviour explicit--
```
:param <bool> cids_all: boolean parameter that outlines whether all cross-sections
  should be used for the relative value calculation. Default is False. If True,
  the cids parameter is ignored.
```
