### ISSUE TITLE
Make_zn_scores taking too long

### ISSUE THREAD

**Issue by rushilg99** [macrosynergy/macrosynergy#707]
Takes 2 mins 45 secs to run:

df_mbase_d1m1ml3_zn = msp.make_zn_scores(
    df=dfd,
    xcat="MBASEGDP_SA_D1M1ML3",
    cids=cidx,
    start=start_date,
    pan_weight=0,
    neutral="mean",
    thresh=3,
)

**Comment by Magnus167** [comment]
Can you please share context (cidx = ? , start_date = ?, what was the msp object initialized with ? )
