### ISSUE TITLE
view_timelines: order of xcats and xcat_labels inconsistent

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#725]
xcat_labels are incorrectly applied to the xcats in view timelines, when there is a single cross-section.
See below: FYI core should be a lot less volatile than headline.

![Image](https://user-images.githubusercontent.com/27678335/232098605-6cd9be68-7ade-4e55-9f13-c4a5d730014d.png)

The mix-up does not happen if there is more than one cross section:

![Image](https://user-images.githubusercontent.com/27678335/232099444-9f8ed856-353e-43aa-ae7f-9d664f0af414.png)

**Comment by Magnus167** [comment]
I'm unable to reproduce this behaviour.
Currently, running the following code:

```python
from macrosynergy.management.simulate_quantamental_data import make_test_df
import pandas as pd
from macrosynergy.management import view_timelines

aud_xr : pd.DataFrame = make_test_df(cids=['AUD'], 
                        xcats=['XR',], 
                        start_date='2010-01-01',
                        end_date='2020-01-01', 
                        prefer='linear')
# aud_xr will be an increasing line from 2010 to 2020.

aud_cry : pd.DataFrame = make_test_df(cids=['AUD'],
                        xcats=['CRY'],
                        start_date='2015-01-01',
                        end_date='2020-01-01',
                        prefer='decreasing-linear')
# aud_cry will be a decreasing line from 2015 to 2020.

aud_df : pd.DataFrame = pd.concat([aud_xr, aud_cry])       

view_timelines(aud_df, xcats=['XR', 'CRY'], cids='AUD',
               size=(10, 5), title='AUD Return and Carry')

view_timelines(aud_df, xcats=['XR', 'CRY'], cids=['AUD'],
               xcat_labels=['Return', 'Carry'],
            size=(10, 5), title='AUD Return and Carry')
```
produces these charts (in order):

<img width="916" alt="Screenshot 2023-04-23 at 00 58 00" src="https://user-images.githubusercontent.com/23239946/233812412-cf67bb25-a7de-45f7-8a32-6e135feb3b5f.png">

<img width="899" alt="Screenshot 2023-04-23 at 00 58 12" src="https://user-images.githubusercontent.com/23239946/233812416-bedb3309-fdb2-4d5d-b1c4-1d03c38fe5b6.png">

**Comment by rsueppel** [comment]
Use https://github.com/macrosynergy/macrosynergy/tree/bug_230425_timelines to replicate.
