### ISSUE TITLE
return_beta() flexibility and missing argument

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#745]
Two issues:

- [x]  At present the function throws an error when the data frame contains any more columns than the four required ones: ["cid", "xcat", "real_date", "value"]. This is too restrictive and the redundant columns should just be removed and ignored,
- [x]  The lookback window for the beta estimation grows with the available data set, but it should be limited by a max_obs argument

:param <int> max_obs: the maximum number of latest observations allowed in order to
        estimate a hedge ratio. The default value is 1000.

**Comment by Magnus167** [comment]
[1] Done. Should a warning be raised when dropping the extra columns?
