### ISSUE TITLE
SignalReturnrelations summary table rows mixed up

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#822]
The sequence of rows used to be Panel, Mean years, Positive ratio (for years), Mean cids, Positive ratio (for cids).

![Image](https://user-images.githubusercontent.com/27678335/239539627-d4e61d76-9591-47f4-8c8d-f140dace9ed3.png)

**Comment by Magnus167** [comment]
Will be implementing to go in before https://github.com/macrosynergy/macrosynergy/pull/819
