### ISSUE TITLE
view_timelines issue

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#873]
The following irregular plotting shows:

all_xticks=False removes also the xticks of the last row

![Image](https://user-images.githubusercontent.com/27678335/247097704-c0f0c701-cf7d-461d-83e6-5c8c133d5948.png)

x-axis no longer has the same timelines: we want all charts to reflect the same time period

![Image](https://user-images.githubusercontent.com/27678335/247097967-260c331b-738f-4d1e-b379-a82ac5611039.png)

label_adj argument no longer seems to have an impact on the position of the line color label/legend

**Comment by Magnus167** [comment]
To be closed by PR:#684 , as mentioned in Issue:#924
