### ISSUE TITLE
title_xadj no longer working

### ISSUE THREAD

**Issue by rushilg99** [macrosynergy/macrosynergy#878]
Adjusting title_xadj in the below code does nothing.

xcatx = [
    "WAGES_NSA_P1M1ML12_3MMA",
    "XWAGES_NSA_P1M1ML12_3MMA",
]
cidx = cids_dmeq
sdate = "1990-01-01"

msp.view_timelines(
    dfx,
    xcats=xcatx,
    cids=cidx,
    ncol=3,
    cumsum=False,
    start=sdate,
    same_y=False,
    aspect=2,
    height=3,
    all_xticks=True,
    title="Wage growth, outright and in excess of productivity growth and inflation target, %oya, 3mma",
    title_adj=1.02,
    title_xadj=0.1,
    title_fontsize=18,
    legend_fontsize=17,
    xcat_labels=["Wage growth", "Excess wage growth"],
    label_adj=0.15,
)

**Comment by Magnus167** [comment]
closed by #879
