### ISSUE TITLE
view_timelines futures warning

### ISSUE THREAD

**Issue by lsimonsen** [macrosynergy/macrosynergy#892]
Fix Pandas futures warning from `view_timelines`:
```
C:\ProgramData\Miniconda3\lib\site-packages\seaborn\axisgrid.py:745: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  plot_args = [v for k, v in plot_data.iteritems()]
```

**Comment by Magnus167** [comment]
Closed.
Fix is to use versions of pandas and seaborn from releases that are in "sync" with each other; i.e. - pandas versions from 2023 may not work well with seaborn versions from 2020
