### ISSUE TITLE
Visuals package module

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#924]
Macrosynergy package graphics module

Intention: an efficient matplotlib-based subpackage for the quantamental data format and panels

* We need a lot more functionality around the idea of the quantamental dataframe, or QDF
* Much of our package's code exists to make the "bridge" between a dataframe and a QDF. A significant chunk of it can be optimized to run fast using C-extensions. 
(Much) Later, we might actually want to provide some text/schematic definition of what Macrosynergy considers a QDF to be.

View functions manage calls to more generic functions

* The view functions are implementations of the current "view_" functions scattered around the package. 
* The idea is to "gently" make the direct visuals more and more intuitive for the content developers. 
* We will still allow the familiar "view_" functions to be used and simply pass all their arguments to the new "view." functions.
* Also, visuals functions should specifically be just visual functions. Calculations are andled separately

OOP principles for modulatity and storage

* We "store" a graph for it to be passed to other functions. 
* The object-oriented approach implies : once we create a chart, it will continue to exist as an object, simply to be "re-plotted"
*The modularity, is not very evident at the moment.

The base class implements dataframe reduction and filtering, functions.

Since `PlotterMetaClass` is the metaclass to `Plotter` class, this behaviour is inherited by all subclasses. 

Once a plotter class is instantiated, it can be re-used (typically with a context manager) to create multiple plots with different arguments
* it should allow multiple filterings on the same dataset - thus multiple plots after one instantiation.*

Generic arguments that behave the same across all plotting methods
* Functions are created in a way where the defaults will fit. 
* For most use cases, they will "simply work", without the need for tuning anymore. 
* The plots actively reshape themselves to try and fit everything.

**Comment by rsueppel** [comment]
msv.FacetPlot.lineplot xcat labels seem to get confused, if one does not enter the xcats in alphabetical order. Below growth and inflation have been mixed up:



![Image](https://github.com/macrosynergy/macrosynergy/assets/27678335/114157ca-f61b-4a74-a5b1-8c4716eb4db6)

**Comment by Magnus167** [comment]
`cid_xcat_grid` also does not work as expected when non-existent tickers are passed

**Comment by rsueppel** [comment]
A practically important point for cids/xcats in facet graphs:

In facets, such as those created by view_timelines(), the order of the plots should be the order in which the cross-sections of categories are entered, NOT alphabetical. 

That is because for many applications some countries are more important than others and should be shown first.
