### ISSUE TITLE
Documentation upgrade

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#934]
Improve appearance of https://docs.macrosynergy.com/en/latest/index.html

https://docs.macrosynergy.com/en/latest/
[1] the TOC's first few points all lead to almost the same location and even have duplicate name "context"
=> reduce sections and ensure unique titles
[2] "Getting started" leads to basically no contant
=> scrap

https://docs.macrosynergy.com/en/latest/ref/macrosynergy.dataquery.html
https://docs.macrosynergy.com/en/latest/ref/macrosynergy.dataquery.html#macrosynergy-dataquery-api-module
https://docs.macrosynergy.com/en/latest/ref/macrosynergy.dataquery.html#module-contents
have no content
=> either add or scrap.

https://docs.macrosynergy.com/en/latest/ref/macrosynergy.management.html#submodules and elsewhere
classes and functions are called modules, which seems misleading
=> clarify (=change) name

https://docs.macrosynergy.com/en/latest/ref/macrosynergy.pnl.html
has no content
=> either add or scrap.

**Comment by Magnus167** [comment]
In progress, to be closed by : https://github.com/macrosynergy/macrosynergy/pull/931
